const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM}=require('../.build/qa-runtime/node_modules/jsdom');
const dom=new JSDOM('<main></main>',{runScripts:'outside-only'}),w=dom.window;
let reduced=false,calls=[],cancelled=0,page=-1;
w.matchMedia=()=>({matches:reduced});w.HTMLElement.prototype.animate=function(frames,options){calls.push({frames,options});return {cancel(){cancelled++}}};
w.eval(fs.readFileSync('assets/animation-playback.js','utf8'));
const api=w.AnimationPlayback,host=w.document.querySelector('main');
const player=api.mount(host,[{type:'text',x:10,y:20,w:30,h:10,rotation:25,content:'Test',style:{opacity:.4,fontSize:18},animation:{type:'slideUp',delay:500,duration:900},link:{type:'page',target:2}}],{count:3,goPage:n=>{page=n}});
player.play();assert.equal(calls.length,1);assert.equal(calls[0].options.delay,500);assert.equal(calls[0].options.duration,900);
assert.equal(host.querySelector('.ap-element').style.transform,'rotate(25deg)');assert.equal(host.querySelector('.ap-visual').style.opacity,'0.4');
host.querySelector('.ap-link').click();assert.equal(page,1);
player.play();assert.equal(cancelled,1);reduced=true;player.play();assert.equal(calls.length,2);assert.equal(cancelled,2);
for(const target of ['javascript:alert(1)','data:text/html,test','file:///C:/test'])assert.equal(api.safeLink({type:'url',target},3),null);
assert.equal(api.safeLink({type:'page',target:4},3),null);assert.ok(api.safeLink({type:'url',target:'https://example.com'},3));
assert.equal(api.safeLink({type:'url',target:' example.com/path '},3).target,'https://example.com/path');
const urlPlayer=api.mount(host,[{type:'hotspot',content:'Website',link:{type:'url',target:'example.com'}}],{count:3});
const anchor=host.querySelector('a.ap-link');assert.equal(anchor.href,'https://example.com/');assert.equal(anchor.target,'_blank');assert.equal(anchor.rel,'noopener noreferrer');
urlPlayer.destroy();
player.destroy();assert.equal(host.children.length,0);
reduced=false;calls=[];
const zones=api.mount(host,[{type:'pdfZone',x:10,y:20,w:40,h:5,content:'PDF heading',animation:{type:'pulse',duration:1400}}]);
zones.play();assert.equal(calls.length,2,'zone animates motion and visible emphasis');
assert.equal(calls[1].options.iterations,Infinity);
assert.match(calls[1].frames[1].backgroundColor,/.48/);
const before=cancelled;zones.play();assert.equal(cancelled,before+2,'replay cancels both zone effects');
zones.destroy();assert.equal(host.children.length,0);
w.close();console.log('PASS playback: motion timing, rotation/opacity, replay cleanup, reduced motion, page link, URL validation, visible PDF emphasis');
