const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('../.build/qa-runtime/node_modules/jsdom');
const canvas=require('../.build/qa-runtime/node_modules/@napi-rs/canvas');
global.DOMMatrix=canvas.DOMMatrix;global.Path2D=canvas.Path2D;
const pdfjs=require('../assets/vendor/pdf.min.js');
pdfjs.GlobalWorkerOptions.workerSrc=path.resolve('assets/vendor/pdf.worker.min.js');
const {runtime}=require('./qa-runtime.cjs');
async function main(){
 const dom=new JSDOM(fs.readFileSync('animation.html','utf8'),{url:'http://127.0.0.1:8080/animation.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 const errors=[];w.addEventListener('error',e=>errors.push(e.error));
 const style=w.document.createElement('style');style.textContent=fs.readFileSync('assets/animation-editor.css','utf8');w.document.head.append(style);
 assert.equal(w.getComputedStyle(w.document.querySelector('.topbar')).display,'flex');
 assert.equal(w.getComputedStyle(w.document.querySelector('.ae-inspector .ae-row')).display,'grid');
 assert.equal(w.document.querySelector('#ae-insp-style-sec').closest('.ae-row'),null);
 assert.equal(w.document.querySelectorAll('#ae-insp-style-sec').length,1);
 w.Blob=Blob;w.Uint8Array=Uint8Array;w.ArrayBuffer=ArrayBuffer;w.matchMedia=()=>({matches:false});
 w.URL.createObjectURL=URL.createObjectURL;w.URL.revokeObjectURL=URL.revokeObjectURL;
 w.JSZip=require('../assets/vendor/jszip.min.js');w.eval(fs.readFileSync('assets/vendor/pdf-lib.min.js','utf8'));
 w.pdfjsLib={OPS:pdfjs.OPS,GlobalWorkerOptions:{},Util:pdfjs.Util,getDocument:options=>pdfjs.getDocument({...options,disableFontFace:false,verbosity:0,canvasFactory:new class{create(width,height){const c=canvas.createCanvas(width,height);return {canvas:c,context:c.getContext('2d')}}reset(obj,width,height){obj.canvas.width=width;obj.canvas.height=height}destroy(obj){obj.canvas.width=0;obj.canvas.height=0}}})};
 Object.defineProperty(w.HTMLElement.prototype,'clientWidth',{get:()=>1000});Object.defineProperty(w.HTMLElement.prototype,'clientHeight',{get:()=>700});
 w.HTMLElement.prototype.getBoundingClientRect=()=>({left:0,top:0,width:600,height:800});
 w.HTMLCanvasElement.prototype.getContext=function(){if(!this.native||this.native.width!==this.width||this.native.height!==this.height)this.native=canvas.createCanvas(this.width,this.height);const ctx=this.native.getContext('2d');if(!ctx.qaDraw){const draw=ctx.drawImage.bind(ctx);ctx.drawImage=(src,...args)=>draw(src.native||src,...args);ctx.qaDraw=true;}return ctx};
 w.HTMLCanvasElement.prototype.toDataURL=function(){return this.native.toDataURL('image/png')};
 w.HTMLCanvasElement.prototype.toBlob=function(cb){cb(new Blob([this.native.toBuffer('image/jpeg')],{type:'image/jpeg'}))};
 w.Image=class extends canvas.Image{get naturalWidth(){return this.width}get naturalHeight(){return this.height}set src(url){fetch(url).then(r=>r.arrayBuffer()).then(b=>{super.src=Buffer.from(b)})}};
 w.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:async()=>({data:{lines:[]}}),terminate:async()=>{}})};
 let posted=null,saved=null,cancel=false,downloads=0;
 const source=new Blob([fs.readFileSync('.build/qa-office/layout.docx.pdf')],{type:'application/pdf'});
 w.fetch=async(url,options)=>{
  if(url==='/api/capabilities')return new Response(JSON.stringify({office:true,token:'test-token'}));
  if(String(url).startsWith('/api/convert/')){posted={url,options};return new Response(source);}
  if(String(url).startsWith('blob:'))return fetch(url);
  return new Response(fs.readFileSync(path.resolve(String(url))));
 };
 w.showSaveFilePicker=async()=>{if(cancel)throw Object.assign(Error('cancel'),{name:'AbortError'});return {createWritable:async()=>({write:async blob=>{saved=blob},close:async()=>{},abort:async()=>{}})}};
 w.HTMLAnchorElement.prototype.click=function(){downloads++};
 for(const file of ['assets/flipbook-export.js','assets/animation-playback.js','assets/animation-ocr.js','assets/animation-editor.js'])w.eval(fs.readFileSync(file,'utf8'));
 await new Promise(r=>setTimeout(r,10));
 const wait=async(predicate,label)=>{for(let i=0;i<2000;i++){if(predicate())return;await new Promise(r=>setTimeout(r,5))}throw Error(label+' / '+w.document.querySelector('#ae-error').textContent)};
 const input=w.document.querySelector('#ae-doc-file');
 const upload=async(file)=>{Object.defineProperty(input,'files',{configurable:true,value:[file]});input.dispatchEvent(new w.Event('change'));await wait(()=>!input.disabled,'import')};
 const office=new Blob(['source']);office.name='layout.docx';await upload(office);
 assert.equal(posted.url,'/api/convert/word-to-pdf');assert.equal(posted.options.headers['X-Build-Token'],'test-token');assert.equal(posted.options.body,office);
 assert.equal(w.document.querySelectorAll('.ae-strip-btn').length,2,w.document.querySelector('#ae-error').textContent);
 const originalImage=w.document.querySelector('.ae-page-img').src;
 w.document.querySelector('#ae-load-page').click();await wait(()=>!w.document.querySelector('#ae-load-page').disabled,'zones');
 assert.ok(w.document.querySelectorAll('.ae-extracted').length>0);
 assert.ok(w.document.querySelectorAll('.ae-image img').length>0,'embedded document image extracted');
 assert.notEqual(w.document.querySelector('.ae-page-img').src,originalImage,'background is rerendered without matched text');
 const zone=w.document.querySelector('.ae-extracted');assert.ok(parseFloat(zone.style.top)<30,'zone should follow text baseline');
 zone.dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true,clientX:0,clientY:0}));
 w.document.querySelector('#ae-i-anim-type').value='pulse';w.document.querySelector('#ae-i-anim-type').dispatchEvent(new w.Event('change'));
 w.document.querySelector('#ae-load-page').click();await wait(()=>!w.document.querySelector('#ae-load-page').disabled,'reload zones');
 w.document.querySelector('.ae-extracted').dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true}));
 assert.equal(w.document.querySelector('#ae-i-anim-type').value,'pulse');
 assert.equal(w.document.querySelector('#ae-insp-content-sec').classList.contains('ae-hidden-row'),false,'extracted text is editable');
 const extractedContent=w.document.querySelector('#ae-i-content');extractedContent.value='Editable extracted heading';extractedContent.dispatchEvent(new w.Event('input'));
 assert.equal(w.document.querySelector('.ae-extracted.selected .ae-el-content').textContent,'Editable extracted heading');
 w.document.querySelector('#ae-add-hotspot').click();
 const content=w.document.querySelector('#ae-i-content');content.value='Next page';content.dispatchEvent(new w.Event('input'));
 w.document.querySelector('#ae-i-link-type').value='page';w.document.querySelector('#ae-i-link-page').value='2';w.document.querySelector('#ae-i-link-type').dispatchEvent(new w.Event('change'));
 w.document.querySelector('#ae-mode-preview').click();assert.ok(w.document.querySelectorAll('.ap-element').length>0);
 w.document.querySelector('.ap-link').click();assert.match(w.document.querySelector('#ae-page-label').textContent,/2 \/ 2/);
 w.document.querySelector('#ae-mode-edit').click();
 w.document.querySelector('#ae-export').click();await wait(()=>!w.document.querySelector('#ae-export').disabled,'export');assert.ok(saved);
 const zip=await w.JSZip.loadAsync(await saved.arrayBuffer());const data=JSON.parse(await zip.file('book.json').async('string'));
 assert.equal(data.version,2);assert.ok(zip.file('animation-playback.js'));assert.match(await zip.file('index.html').async('string'),/animation-playback.js/);
 assert.ok(data.pages[0].elements.some(el=>el.isExtracted&&el.type==='text'&&el.content==='Editable extracted heading'),'export includes editable extracted text');
 assert.ok(data.pages[0].elements.some(el=>el.type==='image'&&el.src.startsWith('data:image/png;base64,')),'export includes self-contained image');
 for(const [,asset] of (await zip.file('index.html').async('string')).matchAll(/(?:src|href)="([^"]+)"/g))assert.ok(zip.file(asset),'Missing offline asset: '+asset);
 fs.mkdirSync('.build/qa-animation',{recursive:true});fs.writeFileSync('.build/qa-animation/animated-book.zip',Buffer.from(await saved.arrayBuffer()));
 const reader=runtime('assets/export/index.html',null);reader.w.FLIPBOOK_DATA=data;reader.load('assets/animation-playback.js');reader.w.eval(await zip.file('viewer.js').async('string'));reader.pump();
 assert.equal(reader.w.document.querySelector('#error').hidden,true);assert.ok(reader.w.document.querySelector('.ap-link'));
 assert.ok(reader.w.document.querySelector('.ap-image img'),'offline reader renders extracted image');
 reader.w.document.querySelector('.ap-link').click();reader.pump();assert.ok(reader.w.engine.getCurrentPageIndex()>0);assert.equal(reader.errors.length,0);
 reader.w.engine.destroy();reader.w.close();
 cancel=true;saved=null;w.document.querySelector('#ae-export').click();await wait(()=>!w.document.querySelector('#ae-export').disabled,'cancel');assert.equal(saved,null);assert.equal(downloads,0);
 w.document.querySelector('#ae-prev').click();w.document.querySelector('#ae-clear-zones').click();
 assert.equal(w.document.querySelector('.ae-page-img').src,originalImage,'restore uses untouched original image');
 assert.equal(w.document.querySelectorAll('.ae-extracted').length,0);
 const bad=new Blob(['bad']);bad.name='bad.pdf';await upload(bad);assert.ok(w.document.querySelector('#ae-error').textContent);assert.equal(w.document.querySelectorAll('.ae-strip-btn').length,2,w.document.querySelector('#ae-error').textContent);
 const layered=await w.PDFLib.PDFDocument.create(),layerPage=layered.addPage();
 layerPage.drawText('Layered heading',{x:50,y:700,size:30,color:w.PDFLib.rgb(0,0,0)});
 layerPage.drawText('Layered heading',{x:51,y:701,size:30,color:w.PDFLib.rgb(1,0,0)});
 // A Type3 path-painted duplicate bypasses canvas.fillText entirely.
 const {PDFName,PDFNumber}=w.PDFLib,c=layered.context;
 const glyph=c.register(c.flateStream('600 0 0 0 600 700 d1 0 0 600 700 re f'));
 const type3=c.register(c.obj({Type:'Font',Subtype:'Type3',FontBBox:[0,0,600,700],FontMatrix:[.001,0,0,.001,0,0],CharProcs:{A:glyph},Encoding:{Type:'Encoding',Differences:[65,'A']},FirstChar:65,LastChar:65,Widths:[600],Resources:{}}));
 layerPage.drawText('A',{x:100,y:600,size:30});
 const fontKey=layerPage.node.newFontDictionary('Type3Test',type3);
 layerPage.node.addContentStream(c.register(c.flateStream('BT '+fontKey.toString()+' 30 Tf 100 600 Td (A) Tj ET')));
 const layeredFile=new Blob([await layered.save()],{type:'application/pdf'});layeredFile.name='layered.pdf';await upload(layeredFile);
 w.document.querySelector('#ae-load-page').click();await wait(()=>!w.document.querySelector('#ae-load-page').disabled,'layered extraction');
 assert.equal(w.document.querySelectorAll('.ae-extracted').length,2,'each layered text becomes one editable element');
 const bg=await canvas.loadImage(Buffer.from(await (await fetch(w.document.querySelector('.ae-page-img').src)).arrayBuffer()));
 const check=canvas.createCanvas(bg.width,bg.height),checkCtx=check.getContext('2d');checkCtx.drawImage(bg,0,0);
 const pixels=checkCtx.getImageData(0,0,bg.width,bg.height).data;
 assert.ok(pixels.every((value,index)=>index%4===3||value>245),'both original text layers removed from white background');
 const picture=canvas.createCanvas(320,180);const png=new Blob([picture.toBuffer('image/png')],{type:'image/png'});png.name='picture.png';await upload(png);
 assert.equal(w.document.querySelectorAll('.ae-strip-btn').length,1,w.document.querySelector('#ae-error').textContent);assert.match(w.document.querySelector('#ae-status').textContent,/1 halaman siap/);
 assert.ok(w.document.querySelector('#ae-inspector').classList.contains('hidden'),'new document clears stale inspector');
 w.document.querySelector('#ae-load-page').click();await wait(()=>!w.document.querySelector('#ae-load-page').disabled,'image zones');
 assert.match(w.document.querySelector('#ae-action-status').textContent,/OCR selesai/,'image feedback stays visible');
 assert.match(w.document.querySelector('#ae-action-status').textContent,/OCR/,'raster-only page explains missing OCR capability');
 assert.equal(w.document.querySelector('.ae-page-hint'),null,'completed empty extraction must not keep prompting to load');
 w.document.querySelector('#ae-add-text').click();
 assert.equal(w.document.querySelector('#ae-inspector').classList.contains('hidden'),false);
 assert.ok(w.document.querySelector('.ae-el.selected'));
 w.document.querySelector('#ae-mode-preview').click();assert.equal(w.document.querySelectorAll('.ap-element').length,1);
 w.document.querySelector('#ae-mode-preview').click();assert.equal(w.document.querySelectorAll('.ap-element').length,1,'replay replaces old player');
 w.document.querySelector('#ae-clear-zones').click();assert.equal(w.document.querySelectorAll('.ap-element').length,0,'clear exits preview');
 assert.equal(w.document.querySelectorAll('.ae-el').length,1,'clear preserves custom text');
 w.document.querySelector('#ae-extract-region').click();
 const picker=w.document.querySelector('.ae-region-picker');assert.ok(picker);
 picker.dispatchEvent(new w.MouseEvent('pointerdown',{clientX:60,clientY:80,bubbles:true}));
 picker.dispatchEvent(new w.MouseEvent('pointermove',{clientX:240,clientY:320,bubbles:true}));
 picker.dispatchEvent(new w.MouseEvent('pointerup',{clientX:240,clientY:320,bubbles:true}));
 await wait(()=>!w.document.querySelector('#ae-extract-region').disabled,'manual region');
 assert.ok(w.document.querySelector('.ae-image img'),'any raster region becomes an image element');
 assert.equal(errors.length,0,String(errors));w.close();
 console.log('PASS animation: Office protocol, real PDF render/zones, reload preservation, preview links, exported v2 reader, cancel, invalid recovery, image-to-PDF');
}
main().catch(e=>{console.error(e);process.exit(1)});
