const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
global.JSZip = require('../assets/vendor/jszip.min.js');
require('../assets/flipbook-export.js');
const api = global.FlipbookExport;
require('../assets/export/layout.js');
const pages=Array.from({length:8},()=>({dataset:{},classList:{add(){}}}));
FlipbookLayout.decorate(pages);
assert.deepEqual(pages.map(page=>page.dataset.density),['hard','hard','soft','soft','soft','soft','hard','hard']);
assert.equal(FlipbookLayout.motion(false).useMouseEvents,true);
assert.equal(FlipbookLayout.motion(true).flippingTime,1);
assert.equal(FlipbookLayout.geometry(1920,1080,.7,0,8).single,false);
assert.deepEqual(FlipbookLayout.geometry(1920,1080,.7,0,8),FlipbookLayout.geometry(1920,1080,.7,1,8));
assert.deepEqual(FlipbookLayout.geometry(1920,1080,.7,7,8),FlipbookLayout.geometry(1920,1080,.7,1,8));
assert.equal(FlipbookLayout.geometry(1920,1080,.7,1,8).single,false);
assert.equal(FlipbookLayout.geometry(390,844,.7,1,8).single,true);
assert.equal(FlipbookLayout.geometry(1920,1080,2.5,1,8).single,true);
assert.equal(FlipbookLayout.geometry(3840,2160,.7,1,8).maxWidth,3840);
const model = {version:1,title:'Buku <uji> & "offline"',pageCount:3,ratio:.72,overlays:{'1':{label:'Peserta </script>',value:1250,position:'bottom-right'}}};
const realFetch = global.fetch;
global.fetch = async path => {
  if (path.startsWith('test:')) return new Response(new Uint8Array([255,216,255,224,255,217]));
  return new Response(fs.readFileSync(require('node:path').join(__dirname,'..',path)));
};
(async()=>{
  assert.throws(()=>api.validate({...model,pageCount:0}));
  assert.throws(()=>api.validate({...model,overlays:{'3':model.overlays['1']}}));
  assert.throws(()=>api.validate({...model,overlays:{'1':{...model.overlays['1'],position:'bad'}}}));
  assert.throws(()=>api.validate({...model,overlays:{'1':{...model.overlays['1'],value:Infinity}}}));
  const pdf = new Blob(['%PDF-fixture'],{type:'application/pdf'});
  const saved = await api.saveProject(model,pdf);
  const restored = await api.readProject(saved);
  assert.deepEqual(restored.data,model);assert.equal(await restored.pdf.text(),await pdf.text());
  const bundle = await api.packageBook(model,['test:1','test:2','test:3']);
  const zip = await JSZip.loadAsync(await bundle.arrayBuffer());
  for(const file of ['index.html','viewer.js','viewer.css','book-data.js','book.json','page-flip.browser.js','pages/1.jpg','pages/3.jpg','PAGEFLIP-LICENSE.txt'])assert.ok(zip.file(file),file);
  const script = await zip.file('book-data.js').async('string');assert.ok(!script.includes('</script>'));
  const context={window:{}};vm.runInNewContext(script,context);
  assert.equal(context.window.FLIPBOOK_DATA.overlays['1'].label,'Peserta </script>');
  const html = await zip.file('index.html').async('string');
  for(const [,file] of html.matchAll(/(?:src|href)="([^"]+)"/g))assert.ok(zip.file(file),'offline asset '+file);
  await assert.rejects(()=>api.readProject(bundle));
  await assert.rejects(()=>api.packageBook(model,['test:1']));
  console.log('PASS project round-trip, manifest validation, offline package, escaped script data, asset completeness');
})().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{global.fetch=realFetch});
