const assert=require('node:assert/strict');
const {runtime}=require('./qa-runtime.cjs');
const t=runtime('assets/export/index.html',null),w=t.w;
let now=0,callback,reading=true,returns=0;
w.Date.now=()=>now;w.setInterval=fn=>{callback=fn;return 1};w.clearInterval=()=>{};
const dispose=w.FlipbookIdle.bind({active:()=>reading,home:()=>{returns++;reading=false}});
const overlay=w.document.querySelector('.book-idle');
now=169999;callback();assert.equal(overlay.hidden,true);
now=170000;callback();assert.equal(overlay.hidden,false);assert.match(overlay.textContent,/10/);
w.document.dispatchEvent(new w.Event('pointerdown'));assert.equal(overlay.hidden,true);
now=349999;callback();assert.equal(returns,0);
now=350000;callback();assert.equal(returns,1);assert.equal(overlay.hidden,true);
now=900000;callback();assert.equal(returns,1);
reading=true;now=1070000;callback();assert.equal(overlay.hidden,false);
overlay.querySelector('button').click();assert.equal(overlay.hidden,true);
now=1240000;callback();assert.equal(returns,1);
now=1250000;w.document.dispatchEvent(new w.Event('visibilitychange'));assert.equal(returns,2);
dispose();assert.equal(w.document.querySelector('.book-idle'),null);w.close();
console.log('PASS idle warning, exact timeout, activity/continue reset, cover suppression, background deadline, cleanup');
