const assert=require('node:assert/strict');
require('../assets/flipbook-export.js');
const api=global.FlipbookExport;
(async()=>{
  assert.equal(await api.chooseSave('book.zip'),null);
  let options,bytes,closed=false,aborted=false;
  const handle={createWritable:async()=>({write:async blob=>{bytes=await blob.text()},close:async()=>{closed=true},abort:async()=>{aborted=true}})};
  global.showSaveFilePicker=async value=>{options=value;return handle};
  assert.equal(await api.chooseSave('custom.flipbook'),handle);
  assert.equal(options.suggestedName,'custom.flipbook');
  global.showSaveFilePicker=async()=>{throw new DOMException('embedded browser','SecurityError')};
  assert.equal(await api.chooseSave('book.zip'),null,'restricted picker falls back to normal download');
  global.showSaveFilePicker=async()=>{throw new DOMException('unsupported','NotSupportedError')};
  assert.equal(await api.chooseSave('book.zip'),null);
  assert.equal(await api.saveBlob(new Blob(['book']),'custom.flipbook',handle),true);
  assert.equal(bytes,'book');assert.equal(closed,true);assert.equal(aborted,false);
  await assert.rejects(()=>api.saveBlob(new Blob(['book']),'book.zip',{createWritable:async()=>({write:async()=>{throw Error('disk full')},abort:async()=>{aborted=true}})}),/disk full/);
  assert.equal(aborted,true);
  let fetched=false;
  global.fetch=async()=>{fetched=true;return new Response('artifact')};
  global.showSaveFilePicker=async()=>{throw new DOMException('cancel','AbortError')};
  await assert.rejects(()=>api.saveRemote('/artifact','book.apk'),{name:'AbortError'});
  assert.equal(fetched,false);
  const chunks=[];
  global.showSaveFilePicker=async()=>({createWritable:async()=>new WritableStream({write(chunk){chunks.push(chunk)}})});
  assert.equal(await api.saveRemote('/artifact','book.apk'),true);
  assert.equal(Buffer.concat(chunks).toString(),'artifact');
  delete global.showSaveFilePicker;
  let clicked=false;
  global.document={body:{append(){}},createElement(){return {click(){clicked=true},remove(){}}}};
  assert.equal(await api.saveRemote('/artifact','book.apk'),false);assert.equal(clicked,true);
  console.log('PASS custom filename, selected-handle write, write failure cleanup, cancel without download, streamed APK/ZIP save, fallback');
})().catch(error=>{console.error(error);process.exitCode=1});
